### ISSUE TITLE
Public asset generator

### ISSUE THREAD

**Issue by gummybears** [znly/go-sprockets#1]
Ran the example from the public generator on my assets (css,javascript) with an index file application.css and application.js (with require directives on css and javascript). The result is all the assets are copied to the public directory. All the assets are copied, also the ones referenced via require directives. The stylesheets are not minified. Not sure what I am doing wrong

**Comment by bennyscetbun** [comment]
hi sorry for the very late response. i havent seen the github email :(
if you are still on it:
Can you share your project or a small sample with me to check what could be wrong??

**Comment by gummybears** [comment]
Thanks for the reply, in the meantime wrote my own asset pipeline for Go.
You can close the ticket.
